my:
  server:
    addr: localhost
spring:
  datasource:
    url: jdbc:mysql://${my.server.addr}:3306/mall_ams?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 747641
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${my.server.addr}:18848
  application:
    name: mall-ams
  jackson:
    # 总是显示
    default-property-inclusion: always
  redis:
    host: ${my.server.addr}
    port: 16379

dubbo:
  application:
    name: mall-ams
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://${my.server.addr}:18848
    #添加一行配置,尝试去掉nacos的无效配置文件,否则容易nacos配置占满
    use-as-config-center: false
    use-as-metadata-center: false
  consumer:
    check: false
logging:
  level:
    cn.tedu.mall: trace